### ISSUE TITLE
Typo in "int" typename for french translation

### ISSUE THREAD

**Issue by gabyfle** [Supercip971/Cpp-Translate#21]
Hi,

On the screenshot you put in the README, there is a typo.

`int` is translated as `intégral` instead of `entier`

**Comment by Supercip971** [comment]
In French the word `intégral` is a synonym of `entier` (I think)

**Comment by gabyfle** [comment]
@Supercip971 I don't know if they are synonyms but since we're manipulating numbers, I don't think that using `intégral` is a good idea.
When we talk about integers in french, nobody uses `intégral`: you say `5 est un entier` instead of `5 est un intégral`

**Comment by gabyfle** [comment]
Fixed in: https://github.com/Supercip971/Cpp-Translate/commit/e41d32d9feb3ebb07e3b756a836ee215998f74fe

Thank you for your commitment to free programming for all, without language barriers or other forms of discrimination. You are a hero in the shadows.
